name: ci

on:
  push:
    branches:
      - main

env:
  PROJECT_ID: tucon-cce32
  SERVICE: tuconbackend
  REGION: us-east1

jobs:
  deploy:
    permissions:
      contents: 'read'
      id-token: 'write'

    runs-on: ubuntu-latest
    steps:
    - uses: 'actions/checkout@v4'

    - uses: 'google-github-actions/auth@v2'
      with:
        credentials_json: '${{ secrets.GCLOUD_CREDENTIALS }}'

    - id: 'deploy'
      uses: 'google-github-actions/deploy-cloudrun@v2'
      with:
        region: ${{ env.REGION }}
        service: ${{ env.SERVICE }}
        source: ./
